### ISSUE TITLE
Table date filter not working when date is typed

### ISSUE THREAD

**Issue by klopez213** [iTwin/iTwinUI-react#578] opened 2022-03-07 18:28 UTC
#### Describe the bug (actual behavior)
When user filters the date via typing instead of selecting the date in the DatePicker in the table, table isn't getting filtered. Also sorting doesn't work when date filter is enabled.

#### Expected behavior
Table should be filtered. And date column should be sorted properly.

#### Reproduction
[codesandbox](https://codesandbox.io/s/table-datefilter-zf4hq)

##### Steps to reproduce
1. Filter date column via typing instead of selecting the date in the Date Picker. <-- Doesn't filter
1. Filter date column via selecting the date in the Date Picker. <-- This one work.
1. Remove date filter.
1. Sort date column. <-- Doesn't sort properly.  

#### Additional information
Using latest version 1.32.0

**Comment by mayank99** [comment] 2022-03-07 19:08
Hi @klopez213, thanks for the issue.

The date picker behavior is kinda expected until we have a proper `DatePickerInput` component. You can track https://github.com/iTwin/iTwinUI/issues/272 for that.

As for sorting, that is unrelated to this date filter (it will be reproducible even if you remove the `Filter` field). The problem is that you are assigning an empty string (instead of some epoch date) to the accessor and also relying on the default sortType instead of datetime.
```diff
  {
    Header: "Date",
-   accessor: (row) => (row.date ? new Date(row.date) : '',
+   accessor: (row) => (row.date ? new Date(row.date) : new Date(0, 0, 0)),
    Cell: (props) => {
      const date = props.cell.row.original.date;
      return date ? formatDate(new Date(date)) : "";
    },
    Filter: tableFilters.DateRangeFilter({
      translatedLabels,
      placeholder: "M/DD/YYYY",
      formatDate
    }),
    filter: "betweenDate",
    maxWidth: 200,
+   sortType: 'datetime'
  }
```

Alternatively you can try adding a custom sorting function.

**Comment by bentleyvk** [comment] 2022-03-08 07:27
I see you are also missing `parseInput` in `DateFilter` which is required and stated in description:
![image](https://user-images.githubusercontent.com/36186912/157187632-f31a6e63-2085-48f3-a1a0-d1742d1dafdf.png)
Here I fixed your repo https://codesandbox.io/s/table-datefilter-forked-2f7jcb

**Comment by klopez213** [comment] 2022-03-08 14:41
Thank you, your suggestions worked.  Question: Should the `placeholder` depend on the locale?

**Comment by veekeys** [comment] 2022-03-09 12:06
@klopez213 I am closing this issue as seems after adding required props everything works fine.
Feel free to reopen it, if you still face some issues.

**Closed by veekeys** 2022-03-09 12:06 UTC
Labels: bug
