### ISSUE TITLE
Table: Unselect all filtered rows

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI-react#731] opened 2022-07-05 17:47 UTC
The select all button works to first select all rows, then unselect all rows in a table.

When a filter is applied, the select all button only selects all rows, but there is no way to unselect all rows.

![Animation](https://user-images.githubusercontent.com/15036346/177386059-23ae05cb-146e-40bd-b03c-c9bf2c8a8e57.gif)

[Here is a test table](https://codesandbox.io/s/itwinui-react-minimal-example-forked-qwvlr8?file=/src/App.tsx) with selection and filter enabled.

**Comment by bentleyvk** [comment] 2022-07-11 05:50
It works as designed but maybe we should reconsider it.

**Comment by FlyersPh9** [comment] 2022-08-31 19:14
I checked macOS Finder, Microsoft Outlook, and had a member of UX check some areas of Bentley Microstation and found this pattern which might be more clearly understood: A selection is cleared when a filter or search is applied or removed.  The select / deselect all only applies on what is visible from the filter. 

https://user-images.githubusercontent.com/849817/187761559-16e07004-ff6c-4b1e-89c5-2bafab98e015.mov

**Comment by mayank99** [comment] 2022-08-31 19:55
Clearing selection on filter is interesting but i don't think that would help here as Finder doesn't have a _(de)select all_ checkbox.

I think we could go one of two ways:
1. When table is filtered, clicking on the "Select all" checkbox should select _all_ (including hidden) rows in the table (visually go from unchecked to checked). When clicked again, it should deselect the visible rows and show indeterminate state.

OR

2. When table is filtered, clicking on the "Select all" checkbox should only select the visible rows and display as indeterminate state. When clicked again, it should clear the entire selection and show unchecked state.

I think the second approach makes more sense, but I'm fine with either as they are both better than completely disabling the functionality.

The important question here is: _how can we make selection state more clear to the user?_

We might want to consider adding a label somewhere (paginator?) that shows how many rows are selected. Also might want to consider showing a tooltip over the "(de)select all" checkbox to clarify what clicking on it will do.

**Comment by bentleyvk** [comment] 2022-09-05 13:19
I think there is a third way: when table is filtered clicking on "Select All" would select all visible rows and is displayed as checked, so users could easily deselect all of the rows by clicking on the top checkbox again.

**Comment by JoeZman** [comment] 2022-09-07 13:42
Moving this over from [Table: Select-all deselecting doesn't work when filter is applied #616](url)

My 2 cents:
I disagree with the assessment this is a WAD.  From the user's perspective, clicking a button and nothing happens.  That is never a good UI experience obviously.

Because of this bug, multiple tables in Clash Detection are forced to implement **additional** buttons to show and clear all (that actually do clear all).

**Comment by HaveSpacesuit** [comment] 2022-09-09 01:47
Here is how Azure Dev Ops has implemented it. It makes sense to me, other than the bug where removing the filter leads to different items checked.

![ADO filtered select all](https://user-images.githubusercontent.com/15036346/189254936-70d39ba4-82ae-4f9c-b4f2-d8624e313702.gif)

**Comment by HaveSpacesuit** [comment] 2022-09-09 14:57
The ADO table has interesting behavior when starting from a select all state. Adding a filter when all selected shows indeterminate, though if you remove the filter, everything remains selected and still shows indeterminate. I don't think this is good behavior.

If you select all, filter, and unselect all, everything is unselected.

It is unclear which items are actually selected if you select all then add a filter. I'd argue most users would only expect items they can see to be selected. If I select all, add a filter, and try to delete, I would only want the filtered items deleted - same as if I filtered first, then hit select all and delete.

![ADO filtered selection](https://user-images.githubusercontent.com/15036346/189379932-1257007c-59ae-4b4a-bf20-c5ed14859078.gif)

**Comment by JoeZman** [comment] 2022-09-09 15:24
> It is unclear which items are actually selected if you select all then add a filter. I'd argue most users would only expect items they can see to be selected. If I select all, add a filter, and try to delete, I would only want the filtered items deleted - same as if I filtered first, then hit select all and delete.

Agreed, I would assume filtering a column would clear the selection.  Any subsequent select all / delete would only work on (visible) selected rows.

**Comment by mayank99** [comment] 2022-10-10 18:44
@adamhock (and @gretanausedaite, @rohan-kadkol) I think this is not entirely fixed by #864. If some rows that are not in the current filter are selected, then I can't seem to select all rows that _are_ in the current filter.

https://user-images.githubusercontent.com/9084735/194931953-59517a15-8a25-4738-a88a-5ccd68f4772c.mov

**Closed** 2022-10-18 17:19 UTC
Labels: bug
