### ISSUE TITLE
Checkbox ID not being able to be clicked by playwright. 

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#213] opened 2021-07-22 22:43 UTC
#### Describe the bug (actual behavior)
I'm writing e2e test using [playwright](https://playwright.dev/docs/api/class-page). I'm looking for the ID of a iTwinUI's checkbox component where I received the Input element correctly. I try to check it using `await (await page.$("#checkboxID"))?.click()` and I received this error : 
```
    attempting click action
      waiting for element to be visible, enabled and stable
        element is not visible - waiting...
            elementHandle.click: Timeout 30000ms exceeded.
```
Forcing the action does not work. Return this error instead: `elementHandle.click: Element is outside of the viewport`

#### Expected behavior
Calling the click function would do a click on the checkbox and change it's state from unchecked to checked and vice versa.

### Possible solution
I know that selecting the label tag does the same as selecting the input for playwright, thus I can click on the label and change the checkbox that way. The label is displayed and visible because it contain the checkbox span call "iui-checkbox-checkmark". So my proposal is to give an id to the label. Could be a prefix like ``` `label_${props.id}` ``` or suffix like ``` `${props.id}_label` ``` added to the label tag or maybe a new props call labelId?

#### Additional information
Honestly, I wish playwright would allow to use [check()](https://playwright.dev/docs/api/class-page#page-check) and [uncheck()](https://playwright.dev/docs/api/class-page#page-uncheck) without the need to have the element visible, but even with the force arguments, it is still not working.

**Comment by veekeys** [comment] 2021-07-23 11:20
Hi,
Have you tried selecting the checkmark and clicking it?
Something like `#your-checkbox-id + .iui-checkbox-checkmark` ?

**Comment by mayank99** [comment] 2021-07-26 12:46
If `+` doesn't work and you don't want to use `evaluate`, there are other things you can try:
```js
await page.click('label:has('#checkboxId'))
```
```js
await page.click('label:near('#checkboxId'))
```
```js
const checkbox = await page.$('#checkboxId');
const label = await checkbox.getProperty('parentNode');
await label.click();
```

Closing this as it's not a bug in iTwinUI (or even in Playwright), and we've offered five different suggestions.

**Closed by mayank99** 2021-07-26 12:46 UTC
Labels: bug

**Comment by maxime4000** [comment] 2021-07-26 14:11
Sorry I was busy Friday and I forgot to reply. I finally use iui-checkbox:has(#id). I was hoping that check/uncheck function would work on the label as some of the feature like this work for text input, but it does not work... So I come up with a wrapper class that get label for click and get input for isChecked, isIndeterminate. 

Still 2 possible improvement checkbox that could be added here. If Id is defined, label could use for={props.id} and label still have a props for setting an Id on it.
