### ISSUE TITLE
Dropdown menu appearing under subsequent elements

### ISSUE THREAD

**Issue by S-Bra** [iTwin/iTwinUI-react#500] opened 2022-01-05 16:07 UTC
Dropdown hosted in a ButtonGroup that is opening across the table is unusable. 
As soon as the mouse pointer is within the table header, the header is drawn above the menu items. Mouse clicks do not reach the menu item anymore.

#### Expected behavior
Dropdown menu item stay visible on top of the table and can be selected.

#### Reproduction
https://codesandbox.io/s/itwinui-react-more-dropdown-unusable-s1gof?file=/src/App.tsx

##### Steps to reproduce
1. Open the dropdown menu by clicking the "More" button

#### Additional information
Change @itwin/itwinui-react version to 1.27.0 to see previous behavior

**Comment by bentleyvk** [comment] 2022-01-05 16:09
Also, Stephan found that `<ButtonGroup style={{zIndex: 1}}>` is fixing the issue.

**Comment by mayank99** [comment] 2022-01-05 16:28
> Also, Stephan found that `<ButtonGroup style={{zIndex: 1}}>` is fixing the issue.

That will have side effects. For a cleaner workaround, I recommend adding `appendTo={() => document.body}` to the `DropdownMenu`.

The root cause of this issue is the stacking context created by ButtonGroup combined with the popover being placed inside the ButtonGroup. These two ideas work against each other, leading to this frustrating situation.

**Comment by S-Bra** [comment] 2022-01-05 17:13
I confirm that adding `appendTo={() => document.body }` to the `DropdownMenu` fixed the issue

**Comment by mayank99** [comment] 2022-01-24 16:10
> Would this be a part of your button group fixes? If not, seems there is a workaround for this issue, right?

Since we haven't decided what to do with button group, it's hard to tell. But yes, there is a workaround. We were also talking about including it by default in #514

**Comment by veekeys** [comment] 2022-01-24 16:19
Ok, @S-Bra are you ok with current suggestion? Can we close this issue?

**Closed** 2022-02-24 18:41 UTC
Labels: bug, has workaround

**Comment by mayank99** [comment] 2022-02-25 16:06
@S-Bra This is now fixed in 1.32.0
