### ISSUE TITLE
Labeled Multi-Select

### ISSUE THREAD

**Issue by saaaaaally** [iTwin/iTwinUI-react#626] opened 2022-04-14 17:39 UTC
#### Feature
Requesting a Labeled Select that allows you to select multiple options. 
#### Examples
![image](https://user-images.githubusercontent.com/88331924/163443128-3e349254-f570-4e80-bed8-88dfe721f79d.png)

**Comment by mayank99** [comment] 2022-04-14 19:26
Duplicate of #344, so I'm closing this. We are currently working on multi-select so you can subscribe to #344 for updates.

**Closed by mayank99** 2022-04-14 19:26 UTC
Labels: enhancement
