### ISSUE TITLE
ComboBox does not handle change of options correctly

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI-react#709] opened 2022-06-10 15:22 UTC
#### Describe the bug (actual behavior)
ComboBox end up in infinite loop when one of the options is selected and new list of options is passed to ComboBox

#### Expected behavior
ComboBox should not end up in infinite loop.

#### Reproduction
Link to a minimal repro: [SandBox](https://codesandbox.io/s/itwinui-react-example-forked-8frs6w?file=/src/App.tsx)

##### Steps to reproduce
1. Select 'Label 4' in ComboBox
1. Press 'Remove First' button
1. Warnings start appearing in the console: `Maximum update depth exceeded`

**Comment by mayank99** [comment] 2022-06-10 17:10
Hi @saskliutas, thanks for the issue. This looks like a duplicate of #697 which we are currently working on, so you can subscribe to it for updates.

**Comment by mayank99** [comment] 2022-07-12 17:02
Actually this might not be a duplicate, as #697 is about changing the `value` whereas here you are changing the `options` array. We're still looking into it!

**Comment by JonasDov** [comment] 2022-07-13 15:05
Facing the same issue, need a fix of this ASAP.

**Closed** 2022-07-25 14:00 UTC
Labels: bug
