### ISSUE TITLE
Modal backdrop not visible if modal is opened after scrolling

### ISSUE THREAD

**Issue by BentleyVilius** [iTwin/iTwinUI-react#798] opened 2022-08-23 09:06 UTC
#### Describe the bug (actual behavior)
When clicking on Modal, the backdrop will not be displayed on the whole page if modal is not shown in the initial page view.

#### Expected behavior
When clicking on Modal the backdrop would cover the whole page, no matter the Modal position on the page. 

#### Reproduction
https://codesandbox.io/s/itwinui-react-modal-bug-pyy2pz

##### Steps to reproduce
1. Open sandbox, 
2. Click on the second button. (same problem with one button as well)
3. Most of the page is not covered by a backdrop

#### Additional information
Using the newest iTwinUI version. Edge, Chrome, Firefox browsers. 

Possible solution:
Settings these changes in scss fixes the problem (I think):
.iui-backdrop {
  position: fixed;
  height: 100%;
}

**Comment by mayank99** [comment] 2022-08-23 12:34
Closing this as duplicate of https://github.com/iTwin/iTwinUI/issues/738, should be fixed soon-ish.

**Closed by mayank99** 2022-08-23 12:34 UTC
Labels: bug
